Feat/workflows crud/eco 639
trustar/trustar-sdk2-proto pull request #48
Opened 2021-06-01 14:27 UTC by hernantain

2021-06-02 19:11 UTC, imonaco commented on trustar2/handlers/workflows.py
> +    path = "/workflows"
I assume this is intended for private use, maybe rename it to _path?

2021-06-02 19:13 UTC, imonaco commented on trustar2/handlers/workflows.py
> +        self.workflow_guid = workflow_id
Is the ID going to change through the object lifetime? If not, should we call this method only once on the object creation? (__init__)

2021-06-02 19:16 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            self.create_query(Methods.DELETE, "/{}".format(self.workflow_guid))
Python3 best practice is to use f strings, is there any use case for the format method?

2021-06-02 19:17 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            self.create_query(Methods.DELETE, "/{}".format(self.workflow_guid))
same for the other .format appeareances

2021-06-02 19:19 UTC, imonaco approved these changes
Just some minor comments, but LGTM!

2021-06-02 19:58 UTC, hernantain commented on trustar2/handlers/workflows.py
> +        self.workflow_guid = workflow_id
Yes, it can change over the object lifetime.

2021-06-02 19:59 UTC, imonaco commented on trustar2/handlers/workflows.py
> +        self.workflow_guid = workflow_id
Ok!

2021-06-02 20:00 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            self.create_query(Methods.DELETE, "/{}".format(self.workflow_guid))
@imonaco We are still maintaining the SDK compatible with python 2 and 3. It had to be this way, so that we could use it in QRadar. But I think that soon enough we are going to be able to deprecate the python2 compatibility and we a re going to be able to use f-strings and other python3 best practices.

2021-06-02 20:02 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            self.create_query(Methods.DELETE, "/{}".format(self.workflow_guid))
Ok, great, thanks for the clarification!

2021-06-03 15:58 UTC, marcos-vivar approved these changes
Outstanding work @hernantain! 🏆 
:shipit:

2021-06-03 19:23 UTC, manuelramos requested changes
Great job Hernan, just left a few questions. Thanks.

2021-06-03 19:23 UTC, manuelramos commented on trustar2/handlers/workflows.py
> +        self.set_payload_param("safelistGuids", safelist_ids)
What do you think of this idea? Define the mapping of these properties in a separate file. I think that way we would have centralized the definition of the properties of the payloads to send to the API.
You know, in case at some point these properties change their name in the api (which we already know has happened).
Maybe this can turn out to be a big task since I see that we have hardcoded property names over the project. But let me know what you think.

2021-06-03 19:23 UTC, manuelramos commented on trustar2/handlers/workflows.py
> +            - set_updated_to
Nice doc

2021-06-03 19:23 UTC, manuelramos commented on trustar2/trustar.py
> +    def workflows(self):
If we update the name of the class `Workflows`, maybe we should change this fn name too?

2021-06-03 19:58 UTC, imonaco commented on trustar2/handlers/workflows.py
> +class Workflows(BaseHandler):
I second this Idea.

2021-06-03 20:00 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            func()
Do you expect to add more functions to that func tuple? Or why are you doing it this way instead self.set_safelist_ids() ?

2021-06-03 20:32 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            func()
If that was the case, may i suggest creating a func list in the line before for readability?
Like so:

init_functions = ( 
                          self.set_safelist_ids,
                         self.set_another_thing,
                        self.set_bar_foo,
                         )
for func in init_funcs:
    func()

2021-06-03 20:36 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            raise AttributeError("Workflow name's length must be between 3 and 120 characters")
Are this values arbitrary? Can we extract them to constants somewhere else ( maybe at top of the file ) , like MIN_NAME_LENGTH, MAX_NAME_LENGTH ?

2021-06-03 20:36 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            raise AttributeError("Workflow name's length must be between 3 and 120 characters")
Also use them in the error message as vars

2021-06-03 20:38 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            created_from = get_timestamp(created_from)
If created_from IS an int, would get_timestamp also work? In that case can we just do:

`created_from = get_timestamp(created_from)` 

It would better for readbility and debugging

2021-06-03 20:38 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            created_from = get_timestamp(created_from)
I mean, removing the conditional

2021-06-03 20:38 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            created_to = get_timestamp(created_to)
Same as above

2021-06-03 20:39 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            created_to = get_timestamp(created_to)
And all the similar sentences in this file

2021-06-03 20:40 UTC, imonaco commented on trustar2/handlers/workflows.py
> +        self.set_query_param("updatedTo", updated_to)
Do we have a setter for each property or is the user intended to work with set_query_param directly for some param? If it is not, we may rename the set_query_param method as private

2021-06-03 20:42 UTC, imonaco commented on trustar2/models/base.py
> +        if attribute in ("_entity_type", "workflow_type"):
can we extract this tuple to a separate variable to improve readability ? With just 2 values its ok, but when it gets to 3, 4 etc its pretty messy

2021-06-03 20:48 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +
I assume that _handle_list returns a list, and python3 allows to extend a list with  += , but i think that it would be a good practice to just use .extend , It would be much better for future debugging in my opinion.

2021-06-03 20:52 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +        self.priority_scores += priority_scores
Same here as above, I assume because of the init that priority_scores ( also because of the plural ), that it is a list, and you are trying to extend it, but it would be better to read and debug to use a list method, like extend ( or just iterate through it and append, up to you )

2021-06-03 20:54 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +        self.priority_scores += priority_scores
Same comment for all the += in lists

2021-06-03 20:55 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +            raise AttributeError(
Sorry for my ignorance, but what would be the possibles outcomes here ? ( a substraction operation to a set )

2021-06-03 20:56 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +            raise AttributeError("Workflow source config weights have to be within 1 and 5.")
Same here, can we extract these (arbitrary?) into external constants ? and use them also in the error message

2021-06-03 21:40 UTC, hernantain commented on trustar2/handlers/workflows.py
> +        self.set_payload_param("safelistGuids", safelist_ids)
Not sure I got you @manuelramos . Do you mean like defining a mapping of this type:

`set_safelist_ids` --> "safelistGuids"

Something like that? So we go and fetch the param name and we only have to change it in one part?

2021-06-03 21:44 UTC, hernantain commented on trustar2/handlers/workflows.py
> +class Workflows(BaseHandler):
It's a good idea. I did like 'workflows' but I'll change it to be consistent allong all handlers

2021-06-03 21:45 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            func()
Yup, you are right, I'm gonna take the first approach.

2021-06-03 21:45 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            raise AttributeError("Workflow name's length must be between 3 and 120 characters")
Totally agree.

2021-06-03 21:46 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            created_from = get_timestamp(created_from)
In that case `get_timestamp` will not work. But I can move the conditional to that function and avoid having to check in all methods. Gonna think a little bit over that one to make the right call.

2021-06-03 21:47 UTC, hernantain commented on trustar2/handlers/workflows.py
> +        self.set_query_param("updatedTo", updated_to)
Agree

2021-06-03 21:50 UTC, hernantain commented on trustar2/models/workflow_configs.py
> +            raise AttributeError(
The result is going to be a set with the elements of the first argument that are not in the second argument. The idea is that it should be empty because you wouldn't have to be able to put types that trustar do not handle.

2021-06-03 22:09 UTC, imonaco commented on trustar2/handlers/workflows.py
> +            created_from = get_timestamp(created_from)
That would be best, great!

2021-06-03 22:11 UTC, imonaco commented on trustar2/models/workflow_configs.py
> +            raise AttributeError(
Great, thanks! Maybe I would make a method like "are_types_valid" or something to return a boolean, but its ok. Just thinking outloud

2021-06-04 15:15 UTC, manuelramos commented on trustar2/handlers/workflows.py
> +        self.set_payload_param("safelistGuids", safelist_ids)
> So we go and fetch the param name and we only have to change it in one part?

right, That's exactly my point.
Feel free to decide whether to do it in this PR or perhaps it should be done with the story related to returning objects instead of a Response objects?. But we should have something to centralize the name of the properties that we send and receive from the API in order to just change it there in case it necessary , I think. As it suits you best.

2021-06-04 16:18 UTC, hernantain commented on trustar2/handlers/workflows.py
> +        self.set_query_param("updatedTo", updated_to)
I'm gonna tackle this in another PR in the future as I have to change this in all handlers and I don't want to make this PR bigger than it is already.

2021-06-04 16:19 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            created_from = get_timestamp(created_from)
I'm also gonna take this into account for another PR. I have somer other ideas for that function and want to tackle everything one time.

2021-06-04 16:19 UTC, hernantain commented on trustar2/handlers/workflows.py
> +            created_to = get_timestamp(created_to)
Same comment as above.

2021-06-04 16:21 UTC, hernantain commented on trustar2/handlers/workflows.py
> +        self.set_payload_param("safelistGuids", safelist_ids)
Yeah I totally agree, I'm gonna tackle it in another PR as we have to put a little thought on it.. And I should change it across all handlers, and I don't want to make this PR bigger.

2021-06-04 16:26 UTC, manuelramos approved these changes
Great job! Thanks.

2021-06-04 16:27 UTC, imonaco approved these changes
Great Job!

2021-06-04 16:27 UTC, imonaco commented on trustar2/handlers/workflows.py
> +        self.set_query_param("updatedTo", updated_to)
Ok, great!

2021-06-04 18:35 UTC, merged