Feat/missing submission methods/eco 642
trustar/trustar-sdk2-proto pull request #51
Opened 2021-06-16 16:31 UTC by hernantain

2021-06-16 20:56 UTC, imonaco commented on trustar2/handlers/indicators.py
>      def set_sort_order(self, order):
If you agree, lets move this method to the SearchHandler, In observables are the same ( "ASC", "DESC") . Just let me know and I change it in my PR

2021-06-16 20:57 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +        if isinstance(arg, type("")) and arg in enum.members():
Why not just let this line if it is the most comapatible instead of the above one? ( I mean, just erase this `
if isinstance(arg, str) and arg in enum.members():




    
    
      
    <span class="blob-code-inner blob-code-marker" data-code-marker="+">            <span class="pl-k">return</span> <span class="pl-s1">arg</span></span> )`

2021-06-16 21:02 UTC, imonaco requested changes

2021-06-16 21:02 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +    def set_excluded_tags(self, tags):
Here you have a problem if tags is another type of iterable ( a tuple, a list ). It would be [ ( "tag1", "tag2" ) ] in this case.
If you want i can change it in my PR, just doing list(set(tags)) , set will work with both single values and another iterables, and also will remove duplicated values.

2021-06-16 21:02 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +    def set_excluded_tags(self, tags):
The same issue with set_enclave_ids

2021-06-16 21:14 UTC, hernantain commented on trustar2/handlers/indicators.py
>      def set_sort_order(self, order):
I didn't move it to the search handler because for submissions that param does not exist (weird). I don't want users to call on `set_sort_order` on a submission, but if you feel that's a better place for the method, do it.

2021-06-16 21:15 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +        if isinstance(arg, type("")) and arg in enum.members():
Definitely this can be done in a better way. Feel free to change it.

2021-06-16 21:16 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +    def _validate_dates(self):
You can have only `to_date` set. It will take a one year window if I'm not mistaken (that's what I've been told). It does not break for sure.

2021-06-16 21:16 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +    def set_from(self, from_date):
Sure, agreed

2021-06-16 21:18 UTC, imonaco commented on trustar2/handlers/indicators.py
>      def set_sort_order(self, order):
I think the best approach is to move it to search handler, and in submission override it raising a NotImplemented error, what do you say ?

2021-06-16 21:20 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +    def _validate_dates(self):
Sorry i dont understand, In the code, if you dont set from_date , it does not enter in any of the if blocks, why are we sure the from_date is always set ? ( im sure im missing something )

2021-06-16 21:21 UTC, imonaco commented on trustar2/handlers/indicators.py
>      def set_sort_order(self, order):
Something like this: `    def set_sort_order(self, order):
        raise NotImplementedError("Submissions dont support sort order")`

2021-06-16 21:23 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +    def set_excluded_tags(self, tags):
We can change the condition to: 

```python
isinstance(tags, (tuple, list, set))
```
That works ☝️ 

And cover all iterables. As I mentioned we can not be checking all kinds of errors. I think that with basic validations and good official docs (not the one that we have right now) code shouldn't be too prone to error. The case that you mentioned is totally valid though. Feel free to change it your way or mine.

2021-06-16 21:23 UTC, hernantain commented
@imonaco I agree with most of your changes, feel free and change them in your PR. Let me know if you want me to change one in this one.

2021-06-16 21:25 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +    def set_from(self, from_date):
btw, this is the place where it should be changed https://github.com/trustar/trustar-sdk2-proto/blob/main/trustar2/base.py#L17

2021-06-16 21:27 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +    def _validate_dates(self):
If you only set `to_date`, the API will take care of the rest and make a 1 year window that ends in your `to_date` date

2021-06-16 21:29 UTC, hernantain commented on trustar2/handlers/indicators.py
>      def set_sort_order(self, order):
Sure, do it.

2021-06-16 21:56 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +    def _validate_dates(self):
Great

2021-06-16 21:59 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +    def set_excluded_tags(self, tags):
Yeah, i thought about your solution at first , but I dont really like to be checking again and again. I know that we cant validate 100% of cases, but lets try to validate these easy ones.

2021-06-16 21:59 UTC, imonaco commented
> @imonaco I agree with most of your changes, feel free and change them in your PR. Let me know if you want me to change one in this one.

Thanks @hernantain , apart from these changes, all the rest is LGTM. Great Job!

2021-06-16 23:00 UTC, manuelramos approved these changes
Good job. 
Just leave a couple of comments/suggestions for a better reading of the code. But I am approving of this PR anyway.
Thanks for the tests.

2021-06-17 15:02 UTC, hernantain commented on tests/unit/test_submission.py
> +    assert len(submission.payload_params) == TOTAL_DEFAULT_PARAMS + 1
When you instantiate a Submission object, the `set_tags` method is called because `tags` is a required field (it can be empty but is required). So, it's much more friendlier to set it by default than making the user call `set_tags([])`. Of course that if you need to set tags you can just override the empty value by calling `set_tags(["tag1", "tag2"])`. We have `TOTAL_DEFAULT_PARAMS + 1` just to make it clear that calling one setter should only add one element.

2021-06-17 15:20 UTC, hernantain commented on tests/unit/test_submission.py
> +BASE_URL = "https://api.trustar.co/api/2.0/submissions{}"
Done!

2021-06-17 15:40 UTC, marcos-vivar commented on tests/conftest.py
> +BASE_URL = "https://api.trustar.co/api/{}".format(API_VERSION)
Quick quesiton:
```python
API_VERSION = "2.0"
BASE_URL = f"https://api.trustar.co/api/{API_VERSION}"
```

2021-06-17 15:41 UTC, marcos-vivar commented on tests/conftest.py
> +BASE_URL = "https://api.trustar.co/api/{}".format(API_VERSION)
> Quick quesiton:
> 
> ```python
> API_VERSION = "2.0"
> BASE_URL = f"https://api.trustar.co/api/{API_VERSION}"
> ```

Forgot about **Python 2** support.

2021-06-17 15:46 UTC, marcos-vivar commented on tests/conftest.py
> +BASE_URL = "https://api.trustar.co/api/{}".format(API_VERSION)
I just was the concatenation for endpoints creation! 👍🏽

2021-06-17 17:22 UTC, imonaco approved these changes
We agreed on some changes in another PR, LGTM!

2021-06-17 17:24 UTC, merged