[ECO-643] Implement Observables Handler
trustar/trustar-sdk2-proto pull request #52
Opened 2021-06-17 19:17 UTC by imonaco

### What ?

Implement methods to interact with observables related operations.

### Why ?

We are lacking a handler to interact with the observables API

### How ?

Creating a new handler, and refactor a bit. Also add more test cases!

2021-06-17 19:56 UTC, hernantain requested changes
Great Work @imonaco 💯 ! Looking good! Just have some minor comments. (Sorry for all the newline at "eof" comments, just want github to stop complaining)

2021-06-17 19:56 UTC, hernantain commented on tests/unit/test_submission.py
> +    assert len(submission.payload_params) == TOTAL_DEFAULT_PARAMS
EOF

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +
Empty lines

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/submission.py
> +        raise NotImplementedError("Submissions dont support sort order")
EOF

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/tags.py
> +        return "{}{}".format(self.base_url, "/alter-tags")
eof

2021-06-17 19:56 UTC, hernantain commented on trustar2/trustar_enums.py
> +    UNRECOGNIZED = "UNRECOGNIZED"
eof

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/observables.py
> +            LAST_SEEN = "LAST_SEEN"
Can we move this one to: `trustar2/trustar_enums.py`

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/observables.py
> +        types = list(map(lambda t: self._get_value(t, ObservableTypes), set(types)))
nice

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/observables.py
> +        MAX_TAG_LENGTH = 20
We have an enum with this value [here](https://github.com/trustar/trustar-sdk2-proto/blob/main/trustar2/trustar_enums.py#L58)

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +        return date if isinstance(date, int) else get_timestamp(date)
Nice! Can we move this methods into the `BaseHandler` class? This is applicable for lots of things not only search params.

2021-06-17 19:56 UTC, hernantain commented on tests/unit/test_tags.py
> +EXPECTED_URL = BASE_URL + "{}" + "/{}/alter-tags".format(IOC_SUBMISSION_GUID)
I did a last minute change of this in my last PR and included a BASE_URL string in `conftest.py`

2021-06-17 19:56 UTC, hernantain commented on tests/conftest.py
> +    )
Nice

2021-06-17 19:56 UTC, hernantain commented on tests/unit/resources.py
> +}"""
eof

2021-06-17 19:56 UTC, hernantain commented on tests/unit/test_observables_handler.py
> +    assert(q.query_string.get("submissionId") ==  submission_id)
EOF

2021-06-17 19:56 UTC, hernantain commented on tests/unit/test_observables_handler.py
> +    MAX_TAGS = 20
Can we move MAX_TAGS to a constant at module level so we don't have to repeat it everytime? We can even do something like:

```python
from trustar2.trustar_enums import MaxValues

MAX_TAGS = MaxValues.TAGS.value
```

2021-06-17 19:56 UTC, hernantain commented on tests/unit/test_tags.py
> +    EXPECTED_URL = "{}{}/{}".format(BASE_URL, "observables", "alter-tags")
Should be also changed here.

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/search_handler.py
> +        return date if isinstance(date, int) else get_timestamp(date)
Also, maybe you can move the logic of `_process_date` to [here](https://github.com/trustar/trustar-sdk2-proto/blob/main/trustar2/base.py#L12)

2021-06-17 19:56 UTC, hernantain commented on trustar2/handlers/tags.py
> +
Can you add this import on `trustar2.__init__.py` and `trustar2.handlers.__init__.py` ?

2021-06-17 20:01 UTC, imonaco commented on tests/unit/test_submission.py
> +    assert len(submission.payload_params) == TOTAL_DEFAULT_PARAMS
yeah, mb haha, fixing all them in a minute

2021-06-17 20:01 UTC, imonaco commented on tests/unit/test_submission.py
> +    assert len(submission.payload_params) == TOTAL_DEFAULT_PARAMS
we should consider implementing a linter such as black

2021-06-17 20:02 UTC, imonaco commented on tests/unit/test_observables_handler.py
> +    MAX_TAGS = 20
Yeah, i wanted to do that, but then i thought that not all the tags for every entity has 20 as max, any suggestions about this issue? or all has the same?

2021-06-17 20:03 UTC, imonaco commented on trustar2/handlers/tags.py
> +
Oh right, the imports, sorry, total forgot about that

2021-06-17 20:13 UTC, imonaco commented on tests/unit/test_observables_handler.py
> +    MAX_TAGS = 20
I just look into the enum file and it already exists, lol, im changing it right now

2021-06-17 20:16 UTC, marcos-vivar commented on tests/conftest.py
> +    )
Nice indeed!

2021-06-17 20:23 UTC, marcos-vivar approved these changes
Outstanding work @imonaco! 👍🏽 

Minor comments but LGTM! :shipit:

2021-06-17 20:23 UTC, imonaco commented on trustar2/handlers/__init__.py
> +from trustar2.handlers.observables import ObservablesHandler
omg , they keep appearing haha

2021-06-17 20:25 UTC, imonaco commented on trustar2/handlers/observables.py
> +            LAST_SEEN = "LAST_SEEN"
Yes!

2021-06-17 20:25 UTC, imonaco commented on trustar2/handlers/search_handler.py
> +        return date if isinstance(date, int) else get_timestamp(date)
Will do

2021-06-17 20:31 UTC, imonaco commented on tests/unit/test_tags.py
> +EXPECTED_URL = BASE_URL + "{}" + "/{}/alter-tags".format(IOC_SUBMISSION_GUID)
let me check this

2021-06-17 20:37 UTC, imonaco commented on tests/unit/test_tags.py
> +EXPECTED_URL = BASE_URL + "{}" + "/{}/alter-tags".format(IOC_SUBMISSION_GUID)
done

2021-06-17 21:11 UTC, hernantain commented on trustar2/handlers/observables.py
> +class ObservablesHandler(SearchHandler):
Just realized, shouldn't we be naming this just `Observables` to have consistency with all handlers?

2021-06-18 16:52 UTC, imonaco commented on trustar2/handlers/observables.py
> +class ObservablesHandler(SearchHandler):
Yeah... I wanted to have a talk with you about naming convention, it seems to be a bit irregular, but yes, you are right.

2021-06-18 16:58 UTC, hernantain approved these changes
Great work @imonaco ! LGTM

2021-06-18 17:00 UTC, merged