Feat/python objects response/eco 644
trustar/trustar-sdk2-proto pull request #56
Opened 2021-06-30 02:23 UTC by hernantain

2021-06-30 20:22 UTC, imonaco commented on trustar2/models/entity.py
> +
We can access directly to the entity params now, great!

2021-06-30 20:24 UTC, imonaco commented on trustar2/models/entity.py
> +
we can extract all this logic, into a generic set method. The method would receive a param name and a value, then proceed to check if itself has the param, and the value is value, and set it.
A caveat for this approach would be, should we accept None as value?

2021-06-30 20:25 UTC, imonaco commented on trustar2/models/entity.py
> +
But it is better than having a lot of ifs ( now we have 3, but we can have the necessity to check for a lot of params in the future )

2021-06-30 20:26 UTC, imonaco commented on trustar2/models/entity.py
> +
Same as here, and we can also create a generic entity_from_dict, that receives a type ( in this case attribute, or obesrvable )

2021-06-30 20:28 UTC, imonaco commented on trustar2/models/indicator.py
> +
In this case, the generic setter would need an adjust, because of the custom conditions, but you can see here the necessity of having some generic method, instead of having these many conditionals.

2021-06-30 20:29 UTC, imonaco commented on trustar2/models/indicator.py
> +
Maybe can the setter receive an optional param such as "clauses" (or else ) that would be a list of lambda functions and if all passes, the set is possible.

2021-07-01 17:53 UTC, marcos-vivar commented on trustar2/models/indicator.py
> +
> Maybe can the setter receive an optional param such as "clauses" (or else ) that would be a list of lambda functions and if all passes, the set is possible.

I like this idea @imonaco! A setter and a validator in the same statement!

2021-07-01 17:56 UTC, marcos-vivar commented on trustar2/models/entity.py
> +
Would it be good to have all strings parameterized in an Enum?

2021-07-01 17:58 UTC, marcos-vivar commented on trustar2/models/prioritized_indicator.py
> +        )
We have lots of repeated strings for the available fields of our objects. Maybe idem: https://github.com/trustar/trustar-sdk2-proto/pull/56/files#r662489066

2021-07-01 17:59 UTC, marcos-vivar commented on trustar2/models/prioritized_indicator.py
> +        serialized.update({"observable": observable, "attributes": attributes})
Nice! 👍🏽

2021-07-01 17:59 UTC, marcos-vivar commented on trustar2/models/submission_details.py
> +        )
Idem https://github.com/trustar/trustar-sdk2-proto/pull/56/files#r662490043

2021-07-01 18:00 UTC, marcos-vivar commented on trustar2/models/submission_details.py
> +        )
Idem https://github.com/trustar/trustar-sdk2-proto/pull/56/files#r662490043

2021-07-01 18:01 UTC, marcos-vivar commented on trustar2/query.py
> +        endpoint = self.endpoint.rsplit("/")[-2]
Instead of a magic number for the index we could define a constant that explains itself: `ENDPOINT_INDEX` or something that you like better.

2021-07-01 18:21 UTC, hernantain commented on trustar2/models/prioritized_indicator.py
> +        )
Definitely! I will create a new PR extracting those string into a enums. I didn't want to include it in this one because it would make the PR even bigger than it is right now.

2021-07-01 20:24 UTC, marcos-vivar approved these changes
Impressive @hernantain! 🥇 
:shipit:

2021-07-01 21:02 UTC, imonaco commented on trustar2/query.py
> +        endpoint = self.endpoint.rsplit("/")[-2]
I like this idea, will be changing it also in my PR haha

2021-07-01 23:57 UTC, manuelramos requested changes
Amaizing work! congrats.
I left some comments to consider if you may. 
I'll try to come up with some ideas for `*SubmissionDetails` classes for tomorrow, if you like. But this is a huge step forward.

2021-07-01 23:57 UTC, manuelramos commented on trustar2/models/indicator.py
> +
Would it be feasible just delegate the responsibility to the `indicator` to check for the existence or not of the value?

2021-07-01 23:57 UTC, manuelramos commented on trustar2/models/prioritized_indicator.py
> +        return str(self)
Same [comment](https://github.com/trustar/trustar-sdk2-proto/pull/56/files#diff-3bd1e3a21d65441c57691600038d09283862126e12df5e6224f35b8c6795ebbdR30) here

2021-07-01 23:57 UTC, manuelramos commented on trustar2/models/prioritized_indicator.py
> +        self.safelisted = safelisted
Should all these params be mandatory in this contructor?

2021-07-01 23:57 UTC, manuelramos commented on trustar2/models/submission_details.py
> +        return str(self)
Same [comment](https://github.com/trustar/trustar-sdk2-proto/pull/56/files#diff-3bd1e3a21d65441c57691600038d09283862126e12df5e6224f35b8c6795ebbdR30) here

2021-07-01 23:57 UTC, manuelramos commented on trustar2/query.py
> +        return [obj.from_dict(i) for i in result.json().get("items")]
We have to find a way to map the way property names come (camelcase) to their `snake case` form. That way we can just do something like
```python
return cls (**ioc_dict)
```
[HERE](https://github.com/trustar/trustar-sdk2-proto/pull/56/files#diff-ce2fae5cf867f743292ba82400cb2fec260504662d584c8d3154910fecefd1a5R52) 
And delegate to the constructor of each class the construction of each object that it needs.

But at the moment I can't think of anything, to be honest.

2021-07-02 16:34 UTC, hernantain commented on tests/unit/test_submission.py
> +    assert response.data == json_response
@manuelramos it depends on what kind of endpoint you are hitting. For example, sometimes you will upsert a submission which result is gonna be a payload like this one: 

```python
{
  "id": <SOME ID>,
  "submissionVersion": 1
}
```

In those cases we don't convert the payload response to a python object. We only put the payload into the data field of the `TruStarResponse` class.

In other cases like getting a submission, it will return a payload that's convertable to a python object, and that's why we call `serialize()` later. To transform the python object into the JSON response. (For testing purposes)

2021-07-02 16:38 UTC, hernantain commented on trustar2/models/entity.py
> +        return str(self)
I get what you are saying Manu, I have no problem moving the logic from __str__ to __repr__. But it's weird to me that if it would be the way you are saying, we should enter an endless recursion between __str__ and __repr__, but anyways I'll change it

2021-07-02 16:39 UTC, hernantain commented on trustar2/models/prioritized_indicator.py
> +        self.safelisted = safelisted
From my perspective they should. Right now while doing the `get()` on the dict payload form the API it will default to None if not present.

2021-07-02 16:41 UTC, hernantain commented on trustar2/query.py
> +        return [obj.from_dict(i) for i in result.json().get("items")]
I thought about this, not entirely sure if it's a good idea. Let's discuss it if you want.

2021-07-02 20:52 UTC, manuelramos commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
Oh sorry @hernantain , I suggested extract the logic in a new utility fn called `typename()` in order to reuse it in different places. Like the following:
```python
from utils import typename
class A:
    ...
    def __repr__(self):
        return f"{typename(self)} (...)"

# In some utility file for example utils.py
def typename(obj):
    return type(obj).__name__
```

2021-07-02 20:54 UTC, marcos-vivar approved these changes
This looks amazing, @hernantain! 👍🏽 
:shipit: 

Those new tests are razon thin! 💯

2021-07-02 22:21 UTC, imonaco approved these changes
Some minor comments, but the generic setters are awesome! Great work @hernantain  !

2021-07-02 22:21 UTC, imonaco commented on trustar2/models/entity.py
> +            if not isinstance(valid_from, int):
Can we just make use of the 'and' operator here? that way it would look more clean without the double indentation.

2021-07-02 22:21 UTC, imonaco commented on trustar2/models/entity.py
> +            entity_type not in ObservableTypes.members()):
Maybe extract all the possible outcomes to a constant outside this method?

2021-07-02 22:21 UTC, imonaco commented on trustar2/models/entity.py
> +
Great!

2021-07-02 22:21 UTC, imonaco commented on trustar2/models/entity.py
> +        )
Can we extract this logic into another method like "get_entity_obj" or something like that? Im think about the future, when we could be having a lot more entity types.

2021-07-02 22:21 UTC, imonaco commented on trustar2/trustar_enums.py
> +    HIGH = "HIGH"
Great enums!

2021-07-12 19:58 UTC, manuelramos commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
@hernantain are you going to take this suggestion into account?

2021-07-13 16:45 UTC, hernantain commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
@manuelramos Sorry just saw that prior comment of yours.. I liked the idea, tried it and it works in python3 but not in python2

2021-07-13 16:45 UTC, hernantain commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
I will keep looking or think a similar way. We still have to push another PR for this ticket

2021-07-13 16:46 UTC, hernantain commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
In python2 it prints "instance" instead of the class name.

2021-07-13 17:17 UTC, manuelramos commented on trustar2/models/entity.py
> +        entity = "Observable" if isinstance(self.validator, ObservableTypes) else "Attribute"
damn python2! 
Alright, seems we can use just
```python
def typename(obj):
    return obj.__class__.__name__
```    

THis way should be compatible with both versions.

2021-07-13 19:27 UTC, manuelramos approved these changes
Looks great , thanks for considering my suggestions. 

There is a typo [here](https://github.com/trustar/trustar-sdk2-proto/pull/56/commits/b6d99c7e9b0cbbae8a043bdde7be1fdd1f7d0dbf#diff-dbc2c00c6a623ea9bdf2ae5fb95cbd512f82735a8242247102112857fb9671beR93) btw :)

2021-07-13 19:27 UTC, manuelramos commented on tests/unit/test_prioritized_indicator.py
> +def test_pripritized_indicator_repr(prioritized_indicator_obj):
typo ? :)

2021-07-13 19:49 UTC, merged