Feat/object responses/eco 728
trustar/trustar-sdk2-proto pull request #59
Opened 2021-07-22 16:20 UTC by hernantain

2021-07-22 16:55 UTC, marcos-vivar commented on tests/unit/models/test_workflow_configs.py
> +    assert wf_src_config.__repr__() == "WorkflowSourceConfig(enclave=test-enclave-id, weight=3)"
This is really neat to read! 👍🏽 @hernantain

2021-07-22 16:55 UTC, marcos-vivar commented on tests/unit/models/test_workflow_model.py
> +    assert workflow_obj.serialize() == workflow_json
Sweet and clean! Outstanding tests @hernantain

2021-07-22 16:56 UTC, marcos-vivar commented on tests/unit/models/test_workflow_model.py
> +    assert workflow_obj.__repr__() == "Workflow(name={}, guid={})".format(NAME, GUID)
This parameterization is awesome! 👌🏽

2021-07-22 16:59 UTC, marcos-vivar commented on trustar2/handlers/submission.py
> +            typename(self),
This wrapper for `obj.__class__.__name__` is simply elegant! 🥇 @hernantain

2021-07-22 17:13 UTC, marcos-vivar approved these changes
This is really awesome! @hernantain 
:shipit:

2021-07-22 17:44 UTC, hernantain commented on trustar2/handlers/submission.py
> +            typename(self),
I agree.. That was @manuelramos idea!

2021-07-22 22:31 UTC, manuelramos requested changes
Great work!
I just left a few small comments if you want to take them into account.
Thanks for those tests, BTW.

2021-07-22 22:31 UTC, manuelramos commented on tests/unit/models/test_safelists.py
> +UPDATED_AT = 1618258235331
Are these values and the one on line `17` unix timestamps? How did you created these values?
I wonder if the method you used is extractable into a function like so that the date is more readable. 

Something like
```python
from tests.unit.resources import get_unix_timestamp
CREATED_AT = get_unix_timestamp(day=1, month=12, year=1986)
```
On that way I can read easily the date, right?

2021-07-22 22:31 UTC, manuelramos commented on tests/unit/models/test_workflow_model.py
> +UPDATED = 1621540733425
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-31d75d01a2dbb831ac501da91d1fde1136f07c38f6d844c9a9c8d265da56cab9R15)

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/account.py
> +        )
I think that it is worth in this case to extract in an `if` statement the value of `data`, perhaps for better legibility.
```python
result_data = result.json()
if result.status_code == STATUS_CODE:
    result_data = [Enclave.from_dict(e) for e in result.json()]
    
return TruStarResponse(
    ...
    data=result_data
)
```

Or something similar?

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/safelist.py
> +        )
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-b12e997d24719d2a53bf260bae90478a7872ecb3404e447a201ff91a0ddbc559R36)

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/safelist.py
> +        )
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-b12e997d24719d2a53bf260bae90478a7872ecb3404e447a201ff91a0ddbc559R36)

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/safelist.py
> +        )
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-b12e997d24719d2a53bf260bae90478a7872ecb3404e447a201ff91a0ddbc559R36)

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/safelist.py
> +        )
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-b12e997d24719d2a53bf260bae90478a7872ecb3404e447a201ff91a0ddbc559R36)

2021-07-22 22:31 UTC, manuelramos commented on trustar2/handlers/workflow.py
> +                else result.json()
Same comment as [here](https://github.com/trustar/trustar-sdk2-proto/pull/59/files#diff-b12e997d24719d2a53bf260bae90478a7872ecb3404e447a201ff91a0ddbc559R36)

2021-07-23 19:19 UTC, hernantain commented on tests/unit/handlers/test_workflow.py
> +    assert [wf.serialize() for wf in response.data] == [wf_response]
Yeah, I think it's the same.

2021-07-23 19:19 UTC, hernantain commented on tests/unit/models/test_enclave.py
> +TYPE = "INTERNAL"
Sure

2021-07-23 19:22 UTC, hernantain commented on tests/unit/models/test_safelists.py
> +UPDATED_AT = 1618258235331
I took them form playing around with the API, I don't even know what those dates are. But given the nature of the tests it's completely fine in my opinion. I mean.. the tests do not have a different behaviour regarding the date input. It's just a setter that has to be a timestamp.

2021-07-23 19:23 UTC, hernantain commented on trustar2/handlers/account.py
> +        )
Mhmm, I think it's the same, but OK

2021-07-23 19:36 UTC, hernantain commented on tests/unit/models/test_safelists.py
> +UPDATED_AT = 1618258235331
Just to clarify a little bit.. I'd totally agree if the test would be date oriented because it will improve readability but in this case the test is regarding serialization, it's exactly the same if the date is A, B or Z.

2021-07-23 19:45 UTC, manuelramos approved these changes
Thanks for considering the suggestions, great work!

2021-07-26 16:56 UTC, merged